# Generated by Django 4.2.30 on 2026-07-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial_storage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GuestbookEntry",
        ),
    ]
