# Generated by Django 4.2.30 on 2026-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=3, unique=True)),
                ("currency_name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=5)),
                ("rate_to_krw", models.DecimalField(decimal_places=4, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["currency_code"],
            },
        ),
    ]
