# Generated by Django 4.2.30 on 2026-07-23 12:09

from decimal import Decimal

from django.db import migrations

SEED_RATES = [
    ("USD", "미국 달러", "$", Decimal("1385.00")),
    ("JPY", "일본 엔 (1엔)", "¥", Decimal("9.10")),
    ("EUR", "유로", "€", Decimal("1500.00")),
    ("CNY", "중국 위안", "¥", Decimal("190.00")),
    ("THB", "태국 바트", "฿", Decimal("38.50")),
    ("VND", "베트남 동 (1동)", "₫", Decimal("0.056")),
    ("HKD", "홍콩 달러", "HK$", Decimal("177.00")),
    ("GBP", "영국 파운드", "£", Decimal("1750.00")),
    ("AUD", "호주 달러", "A$", Decimal("910.00")),
    ("SGD", "싱가포르 달러", "S$", Decimal("1020.00")),
]


def seed_rates(apps, schema_editor):
    ExchangeRate = apps.get_model("currency_calculator", "ExchangeRate")
    for code, name, symbol, rate in SEED_RATES:
        ExchangeRate.objects.update_or_create(
            currency_code=code,
            defaults={
                "currency_name": name,
                "symbol": symbol,
                "rate_to_krw": rate,
            },
        )


def unseed_rates(apps, schema_editor):
    ExchangeRate = apps.get_model("currency_calculator", "ExchangeRate")
    codes = [code for code, *_ in SEED_RATES]
    ExchangeRate.objects.filter(currency_code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("currency_calculator", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_rates, unseed_rates),
    ]
